# Pipeline de déploiement pour Azure avec installation de l’Azure CLI via MSI
trigger:
  branches:
    include:
      - master  # Déclenche le pipeline sur les modifications de la branche principale

pool:
  name: 'Default'  # Utilise le pool d'agents auto-hébergé

steps:
- checkout: self  # Cloner le dépôt

# Télécharger et Installer Azure CLI via MSI sur un agent Windows
- task: PowerShell@2
  displayName: 'Télécharger et installer Azure CLI via MSI'
  inputs:
    targetType: 'inline'
    script: |
      # Vérifier si Azure CLI est déjà installé
      if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
          Write-Output "Azure CLI non trouvé. Téléchargement et installation via MSI..."

          # Supprime le fichier MSI s'il existe déjà
          if (Test-Path -Path AzureCLI.msi) {
              Remove-Item -Force AzureCLI.msi
          }

          # Télécharge le fichier MSI d'installation d'Azure CLI
          Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile AzureCLI.msi

          # Vérification de la validité du fichier MSI
          if (!(Test-Path -Path AzureCLI.msi) -or ((Get-Item AzureCLI.msi).length -eq 0)) {
              Write-Output "Échec du téléchargement de l'Azure CLI. Arrêt du pipeline."
              exit 1
          }

          # Installation silencieuse du MSI
          Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet /norestart'
          Write-Output "Azure CLI installé avec succès."

          # Supprimer le fichier MSI après installation
          Remove-Item -Force AzureCLI.msi
      } else {
          Write-Output "Azure CLI est déjà installé."
      }

# Connexion à Azure
- task: AzureCLI@2
  inputs:
    azureSubscription: 'pipeline-service-connection'  # Nom de la connexion de service configurée
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Cette commande montre l'abonnement Azure actuel pour confirmer la connexion
      az account show

# Déployer les ressources avec un modèle ARM
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    azureSubscription: 'pipeline-service-connection'
    resourceGroupName: 'TP1'  # Nom de votre groupe de ressources
    location: 'East US'  # Région de déploiement
    csmFile: '$(System.DefaultWorkingDirectory)/projet-cloud/vms/azuredeploy.json'  # Chemin vers le fichier ARM Template
    deploymentMode: 'Incremental'  # Utiliser 'Incremental' pour éviter de recréer les ressources existantes
