# Pipeline pour synchroniser le dépôt GitHub avec Azure DevOps
trigger:
  branches:
    include:
      - master  # Se déclenche uniquement sur les commits de la branche master

pool:
  name: 'Default'  # Utilise l'agent auto-hébergé

steps:
# Étape 1 : Cloner le dépôt GitHub en mode miroir
- script: |
    echo "Clonage du dépôt GitHub en miroir"
    git clone --mirror https://github.com/alois-fleury/TP1-environnement-deploiement-applications.git repo.git
  displayName: 'Clone GitHub Repository in Mirror Mode'

# Étape 2 : Pousser les changements vers Azure DevOps
- script: |
    echo "Poussée des changements vers Azure DevOps"
    cd repo.git
    git remote add azure https://aloisfleuryca@dev.azure.com/aloisfleuryca/TP1-8CLD201-Arthur-Alois-Ewen-Osama/_git/TP1-8CLD201-Arthur-Alois-Ewen-Osama
    git push azure --mirror
  displayName: 'Push to Azure DevOps Repository'
