# Pipeline de build
trigger:
  branches:
    include:
      - master  # Déclenche la pipeline sur les modifications de la branche principale

pool:
  name: 'Default'

steps:
- checkout: self  # Cloner le dépôt GitHub

# Installer JDK (nécessaire pour Gradle)
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: '"C:\Users\Allow\Downloads\openjdk-17.0.2_windows-x64_bin.zip"'
    cleanDestinationDirectory: true

# Build et Test avec Gradle
- script: |
    .\projet-cloud\gradlew.bat clean build  # Build le projet et exécute les tests
  displayName: 'Build et Test avec Gradle'