# Pipeline de synchronisation du GitHub avec le Azure Repo
trigger:
  branches:
    include:
      - master  # Se déclenche uniquement sur les commits de la branche master

pool:
  name: 'Default'  # Utilise l'agent auto-hébergé

steps:
# Étape 1 : Cloner le dépôt GitHub
- checkout: none  # Empêche Azure DevOps de faire un checkout par défaut du dépôt Azure DevOps

- script: |
    echo "Synchronisation avec le dépôt GitHub"
    cd repo
    git pull origin master
    displayName: 'Sync GitHub repository'

# Étape 2 : Pousser les changements vers le dépôt Azure DevOps
- script: |
    echo "Poussée des changements vers Azure DevOps"
    git remote add azure https://aloisfleuryca@dev.azure.com/aloisfleuryca/TP1-8CLD201-Arthur-Alois-Ewen-Osama/_git/TP1-8CLD201-Arthur-Alois-Ewen-Osama
    git push azure master --force
    displayName: 'Push to Azure DevOps repository'
